name: docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.3
        with:
          version: 1.1.6
          virtualenvs-in-project: true

      - name: Cache folder
        uses: actions/cache@v3
        id: cache-folder
        with:
          path: |
            ~/.cache/cartes/
          key: ${{ runner.os }}-${{ matrix.python-version }}-cache_cartes

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgdal-dev libgeos-dev libproj-dev proj-bin proj-data
          # upgrade to proj>=8.0 for Cartopy 0.20
          git clone https://github.com/OSGeo/PROJ
          cd PROJ
          git checkout 8.2.1
          mkdir build; cd build
          cmake ..
          cmake --build .
          sudo cmake --build . --target install
          cd ../..
          # https://stackoverflow.com/a/73080089
          poetry config experimental.new-installer false
          poetry install

      - name: Populate cache if need be
        if: steps.cache-folder.outputs.cache-hit != 'true'
        env:
          LD_LIBRARY_PATH: /usr/local/lib
        run: |
          poetry run python -c "from cartes.atlas import default, world_atlas"

      - name: Build pages
        env:
          LD_LIBRARY_PATH: /usr/local/lib
        run: |
          cd docs && poetry run make html

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: cartes-viz/cartes-viz.github.io
          publish_branch: master
          publish_dir: docs/build/html
