name: docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  POETRY_VERSION: "1.3.1"
  PYTHON_VERSION: "3.10"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # virtualenv cache should depends on OS, Python version and `poetry.lock` (and optionally workflow files).
      - name: Poetry Packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.local
            .venv
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache folder for cartes
        uses: actions/cache@v3
        id: cache-folder
        with:
          path: |
            ~/.cache/cartes/
          key: cartes-${{ runner.os }}

      - name: Ubuntu system dependencies
        run: |
          sudo apt update
          sudo apt install -y libgdal-dev libgeos-dev libproj-dev proj-bin proj-data

      - name: Install dependencies
        run: |
          poetry install

      - name: Populate cache if need be
        if: steps.cache-folder.outputs.cache-hit != 'true'
        env:
          LD_LIBRARY_PATH: /usr/local/lib
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run python -c "from cartes.atlas import default, world_atlas"

      - name: Build pages
        env:
          LD_LIBRARY_PATH: /usr/local/lib
        run: |
          # until altair 4.3 is released
          poetry run pip install git+https://github.com/altair-viz/altair.git
          cd docs && poetry run make html

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: cartes-viz/cartes-viz.github.io
          publish_branch: master
          publish_dir: docs/build/html
