name: docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          version: 1.1.6
          virtualenvs-in-project: true

      - name: Cache folder
        uses: actions/cache@v2
        id: cache-folder
        with:
          path: |
            ~/.cache/cartes/
          key: ${{ runner.os }}-${{ matrix.python-version }}-cache_cartes

      - name: Install dependencies
        run: |
          sudo apt install -y libgdal-dev libgeos-dev libproj-dev proj-bin proj-data
          poetry install

      - name: Populate cache if need be
        if: steps.cache-folder.outputs.cache-hit != 'true'
        run: |
          poetry run python -c "from cartes.atlas import default, world_atlas"

      - name: Build pages
        run: |
          cd docs && poetry run make html

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: cartes-viz/cartes-viz.github.io
          publish_branch: master
          publish_dir: docs/build/html
