# This workflows will upload a Python Package using Twine when a release is created

# Maybe one day we will package tar.gz without setup.py
# python -m pip wheel . -w dist --no-deps

name: PyPI Publish

on:
  release:
    types: [created]

jobs:
  deploy:
    environment: pypi-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*.tar.gz dist/*.whl
