name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest # ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9"] #, "3.10" bug in Fiona for now
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          version: 1.1.6
          virtualenvs-in-project: true

      - name: Display Python version
        run: poetry run python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          sudo apt install -y libgdal-dev libgeos-dev libproj-dev proj-bin proj-data
          # upgrade to proj>=8.0 for Cartopy 0.20
          git clone https://github.com/OSGeo/PROJ
          cd PROJ
          git checkout 8.2.1
          mkdir build; cd build
          cmake ..
          cmake --build .
          sudo cmake --build . --target install
          cd ../..
          poetry install

      - name: Style checking
        run: |
          poetry run flake8 cartes
          poetry run isort --check-only cartes
          poetry run black --check cartes

      - name: Type checking
        run: |
          poetry run mypy cartes

      - name: Run tests
        env:
          LD_LIBRARY_PATH: /usr/local/lib
        run: |
          poetry run pytest --cov --cov-report term-missing --ignore=cartes/__main__.py

      - uses: codecov/codecov-action@v1
