name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest # ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          sudo apt install -y libgdal-dev libgeos-dev libproj-dev proj-bin proj-data
          python -m pip install --upgrade pip
          python -m pip install --upgrade numpy pyproj  # dependency for cartopy
          python -m pip install --upgrade pytest codecov pytest-cov
          python -m pip install -e .
      - name: Run tests
        run: |
          pytest --cov --cov-report term-missing --ignore=cartes/__main__.py
      - uses: codecov/codecov-action@v1
